import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// var nodemailer = require('nodemailer');

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to JR Reciclagem<a href="#">
          <br/>
        <br/>
        Esse Site tem 1 endpoint que recebe 
          um parametro(string-email) 
          <br/>
          e dispara do e-mail da empresa JR para 
          <br/>
          o email que recebeu o parâmetro.</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/Robertodalfre"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by &nbsp;&nbsp;  {' '}
          <span className={styles.logo}>
            <Image src="/Frame.svg" alt="FrameDalfre Logo" width={350} height={110} />
          </span>
        </a>
      </footer>
    </div>
    
  )
}

// var remetente = nodemailer.createTransport({
// 			host: 'smtp.mail.yahoo.com',
// 			port: 587,
// 			secure:false,
// 			auth:{
// 			user: 'robertodalfre@yahoo.com.br',
// 			pass: 'cgrpnrybyzhzstqj' }
// 			});
			
	
// 			var emailASerEnviado = {
// 				from: 'robertodalfre@yahoo.com.br',
// 				to: 'robertodalfre@gmail.com',
// 				subject: 'Enviando Email de teste',
// 				text: 'Estou te enviando este email para testar meu aplicativo!!!! ! Favor Desconsiderar. Obrigado!!!!    - Roberto Dalfré',
// 				// attachments: [{
// 				// 	filename: 'screenshot22.png',
// 				// 	path: __dirname +'/Image/screenshot22.png',
// 				// 	cid: 'teste' //my mistake was putting "cid:logo@cid" here! 
// 			  //  }]
// 			};



// 				remetente.sendMail(emailASerEnviado, function(error){
// 					if (error) {
// 					console.log(error);
// 					} else {
// 					console.log('Email enviado com sucesso.');
// 					}
// 				});
